### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by johnapost** [seejamescode/grid-wiz#1]
Hiya, would you be interested if I contribute some unit tests? We met at the AustinJS meetup and I want to get to know this tool better. I'm evaluating its usage for some projects.

**Comment by seejamescode** [comment]
Hey John! Glad you’re peeking around. Yeah, that would be beneficial. I also wish we had visual regression testing using the website if you have any experience with that.

**Comment by johnapost** [comment]
I haven't actually implemented visual regressions before but I have read about it and don't think it would be too bad. I'll start with unit tests for now, though.
